import { FormStyles, SpacingProperty } from '../../global-types/styles';

function getDefaultPadding(): SpacingProperty {
  return new SpacingProperty(12);
}

export const STYLE_TEMPLATE_C: FormStyles = {
  borderRadius: 6,
  horizontalGap: 10,
  verticalGap: 20,
  buttons: [
    {
      default: {
        width: '100%',
        backgroundColor: '#007bff',
        color: '#ff0000',
        borderWidth: 0,
        borderColor: '#007bff',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      hover: {
        width: '100%',
        backgroundColor: '#0069d9',
        color: '#000000',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      focus: {
        width: '100%',
        backgroundColor: '#0069d9',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      active: {
        width: '100%',
        backgroundColor: '#0062cc',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#005cbf',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
    },
    {
      default: {
        width: '100%',
        backgroundColor: '#007bff',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#007bff',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      hover: {
        width: '100%',
        backgroundColor: '#0069d9',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      focus: {
        width: '100%',
        backgroundColor: '#0069d9',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      active: {
        width: '100%',
        backgroundColor: '#0062cc',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#005cbf',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
    },
  ],
  input: {
    default: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#000000',
      borderWidth: 1,
      borderColor: '#CCCCCC',
      fontSize: 14,
      height: 30,
      padding: getDefaultPadding(),
      nsLabel: {
        fontSize: 14,
        color: '#000000',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: 'orange',
      },
    },
    hover: {
      width: '100%',
      backgroundColor: '#F0F0F0',
      color: '#000000',
      borderWidth: 1,
      borderColor: '#CCCCCC',
      fontSize: 14,
      height: 30,
      padding: getDefaultPadding(),
      nsLabel: {
        fontSize: 14,
        color: '#000000',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#CCCCCC',
      },
    },
    focus: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#000000',
      borderWidth: 1,
      borderColor: '#4C9AFF',
      fontSize: 14,
      height: 30,
      padding: getDefaultPadding(),
      nsLabel: {
        fontSize: 14,
        color: '#000000',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#CCCCCC',
      },
    },
    invalid: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#000000',
      borderWidth: 1,
      borderColor: '#FF4C4C',
      fontSize: 14,
      height: 30,
      padding: getDefaultPadding(),
      nsLabel: {
        fontSize: 14,
        color: '#000000',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#CCCCCC',
      },
    },
  },
};
