import { FormStyles, SpacingProperty } from '../../global-types/styles';

function getDefaultPadding(): SpacingProperty {
  return new SpacingProperty(12);
}

export const STYLE_TEMPLATE_A: FormStyles = {
  borderRadius: 50,
  horizontalGap: 10,
  verticalGap: 20,
  buttons: [
    {
      default: {
        width: '100%',
        backgroundColor: '#2F8400',
        color: '#ffffff',
        borderWidth: 0,
        borderColor: '#ffffff',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      hover: {
        width: '100%',
        backgroundColor: '#236100',
        color: '#ffffff',
        borderWidth: 0,
        borderColor: '#ffffff',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      focus: {
        width: '100%',
        backgroundColor: '#2F8400',
        color: '#ffffff',
        borderWidth: 0,
        borderColor: '#ffffff',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      active: {
        width: '100%',
        backgroundColor: '#174000',
        color: '#ffffff',
        borderWidth: 0,
        borderColor: '#ffffff',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
    },
    {
      default: {
        width: '100%',
        backgroundColor: '#EDEDED',
        color: '#707070',
        borderWidth: 0,
        borderColor: '#007bff',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      hover: {
        width: '100%',
        backgroundColor: '#d1d1d1',
        color: '#707070',
        borderWidth: 0,
        borderColor: '#808080',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      focus: {
        width: '100%',
        backgroundColor: '#d1d1d1',
        color: '#707070',
        borderWidth: 0,
        borderColor: '#808080',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
      active: {
        width: '100%',
        backgroundColor: '#8f8f8f',
        color: '#ffffff',
        borderWidth: 0,
        borderColor: '#8f8f8f',
        fontSize: 16,
        height: 40,
        padding: getDefaultPadding(),
      },
    },
  ],
  input: {
    default: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#3d3d3d',
      borderWidth: 1,
      borderColor: '#CCCCCC',
      fontSize: 14,
      height: 40,
      padding: new SpacingProperty(16, 16, 12, 12),
      nsLabel: {
        fontSize: 14,
        color: '#707070',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#b8b8b8',
      },
    },
    hover: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#3d3d3d',
      borderWidth: 1,
      borderColor: '#2F8400',
      fontSize: 14,
      height: 40,
      padding: new SpacingProperty(16, 16, 12, 12),
      nsLabel: {
        fontSize: 14,
        color: '#707070',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#b8b8b8',
      },
    },
    focus: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#3d3d3d',
      borderWidth: 1,
      borderColor: '#2F8400',
      fontSize: 14,
      height: 40,
      padding: new SpacingProperty(16, 16, 12, 12),
      nsLabel: {
        fontSize: 14,
        color: '#707070',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#b8b8b8',
      },
    },
    invalid: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#3d3d3d',
      borderWidth: 1,
      borderColor: '#CCCCCC',
      fontSize: 14,
      height: 40,
      padding: new SpacingProperty(16, 16, 12, 12),
      nsLabel: {
        fontSize: 14,
        color: '#707070',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#b8b8b8',
      },
    },
  },
};
