import { DimensionalProperty, FormStyles } from '../../global-types/styles';
import { TEMPLATE_A_BUTTON_1_ID, TEMPLATE_A_BUTTON_2_ID } from './a.constants';

const DEFAULT_PADDING: DimensionalProperty = new DimensionalProperty(
  20,
  20,
  5,
  5
);

export const STYLE_TEMPLATE_A: FormStyles = {
  borderRadius: 5,
  horizontalGap: 10,
  verticalGap: 20,
  buttons: [
    {
      buttonId: TEMPLATE_A_BUTTON_1_ID,
      defaultStyles: {
        backgroundColor: '#007bff',
        textColor: '#fff',
        borderWidth: 0,
        borderColor: '#007bff',
        fontSize: 16,
        fontColor: '#fff',
        height: 40,
        padding: DEFAULT_PADDING,
      },
      hoverStyles: {
        backgroundColor: '#0069d9',
        textColor: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        fontColor: '#fff',
        height: 40,
        padding: DEFAULT_PADDING,
      },
      focusStyles: {
        backgroundColor: '#0069d9',
        textColor: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        fontColor: '#fff',
        height: 40,
        padding: DEFAULT_PADDING,
      },
      activeStyles: {
        backgroundColor: '#0062cc',
        textColor: '#fff',
        borderWidth: 0,
        borderColor: '#005cbf',
        fontSize: 16,
        fontColor: '#fff',
        height: 40,
        padding: DEFAULT_PADDING,
      },
    },
    {
      buttonId: TEMPLATE_A_BUTTON_2_ID,
      defaultStyles: {
        backgroundColor: '#007bff',
        textColor: '#fff',
        borderWidth: 0,
        borderColor: '#007bff',
        fontSize: 16,
        fontColor: '#fff',
        height: 40,
        padding: DEFAULT_PADDING,
      },
      hoverStyles: {
        backgroundColor: '#0069d9',
        textColor: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        fontColor: '#fff',
        height: 40,
        padding: DEFAULT_PADDING,
      },
      focusStyles: {
        backgroundColor: '#0069d9',
        textColor: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        fontColor: '#fff',
        height: 40,
        padding: DEFAULT_PADDING,
      },
      activeStyles: {
        backgroundColor: '#0062cc',
        textColor: '#fff',
        borderWidth: 0,
        borderColor: '#005cbf',
        fontSize: 16,
        fontColor: '#fff',
        height: 40,
        padding: DEFAULT_PADDING,
      },
    },
  ],
  input: {
    inputId: 'first-name',
    defaultStyles: {
      backgroundColor: '#FFFFFF',
      textColor: '#000000',
      borderWidth: 1,
      borderColor: '#CCCCCC',
      fontSize: 14,
      fontColor: '#000000',
      isBlock: true,
      height: 30,
      padding: DEFAULT_PADDING,
      labelFontSize: 14,
      labelFontColor: '#000000',
      placeholderFontSize: 14,
      placeholderFontColor: '#CCCCCC',
    },
    hoverStyles: {
      backgroundColor: '#F0F0F0',
      textColor: '#000000',
      borderWidth: 1,
      borderColor: '#CCCCCC',
      fontSize: 14,
      fontColor: '#000000',
      isBlock: true,
      height: 30,
      padding: DEFAULT_PADDING,
      labelFontSize: 14,
      labelFontColor: '#000000',
      placeholderFontSize: 14,
      placeholderFontColor: '#CCCCCC',
    },
    focusStyles: {
      backgroundColor: '#FFFFFF',
      textColor: '#000000',
      borderWidth: 1,
      borderColor: '#4C9AFF',
      fontSize: 14,
      fontColor: '#000000',
      isBlock: true,
      height: 30,
      padding: DEFAULT_PADDING,
      labelFontSize: 14,
      labelFontColor: '#4C9AFF',
      placeholderFontSize: 14,
      placeholderFontColor: '#CCCCCC',
    },
    invalidStyles: {
      backgroundColor: '#FFFFFF',
      textColor: '#000000',
      borderWidth: 1,
      borderColor: '#FF4C4C',
      fontSize: 14,
      fontColor: '#000000',
      isBlock: true,
      height: 30,
      padding: DEFAULT_PADDING,
      labelFontSize: 14,
      labelFontColor: '#FF4C4C',
      placeholderFontSize: 14,
      placeholderFontColor: '#CCCCCC',
    },
    validStyles: {
      backgroundColor: '#FFFFFF',
      textColor: '#000000',
      borderWidth: 1,
      borderColor: '#66FF66',
      fontSize: 14,
      fontColor: '#000000',
      isBlock: true,
      height: 30,
      padding: DEFAULT_PADDING,
      labelFontSize: 14,
      labelFontColor: '#66FF66',
      placeholderFontSize: 14,
      placeholderFontColor: '#CCCCCC',
    },
  },
};
