import { SpacingProperty, FormStyles } from '../../global-types/styles';
import { TEMPLATE_A_BUTTON_1_ID, TEMPLATE_A_BUTTON_2_ID } from './a.constants';

const DEFAULT_PADDING: SpacingProperty = new SpacingProperty(12);

export const STYLE_TEMPLATE_A: FormStyles = {
  borderRadius: 5,
  horizontalGap: 10,
  verticalGap: 20,
  buttons: [
    {
      buttonId: TEMPLATE_A_BUTTON_1_ID,
      default: {
        width: '100%',
        backgroundColor: '#007bff',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#007bff',
        fontSize: 16,
        height: 40,
        padding: DEFAULT_PADDING,
      },
      hover: {
        width: '100%',
        backgroundColor: '#0069d9',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        height: 40,
        padding: DEFAULT_PADDING,
      },
      focus: {
        width: '100%',
        backgroundColor: '#0069d9',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        height: 40,
        padding: DEFAULT_PADDING,
      },
      active: {
        width: '100%',
        backgroundColor: '#0062cc',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#005cbf',
        fontSize: 16,
        height: 40,
        padding: DEFAULT_PADDING,
      },
    },
    {
      buttonId: TEMPLATE_A_BUTTON_2_ID,
      default: {
        width: '100%',
        backgroundColor: '#007bff',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#007bff',
        fontSize: 16,
        height: 40,
        padding: DEFAULT_PADDING,
      },
      hover: {
        width: '100%',
        backgroundColor: '#0069d9',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        height: 40,
        padding: DEFAULT_PADDING,
      },
      focus: {
        width: '100%',
        backgroundColor: '#0069d9',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#0062cc',
        fontSize: 16,
        height: 40,
        padding: DEFAULT_PADDING,
      },
      active: {
        width: '100%',
        backgroundColor: '#0062cc',
        color: '#fff',
        borderWidth: 0,
        borderColor: '#005cbf',
        fontSize: 16,
        height: 40,
        padding: DEFAULT_PADDING,
      },
    },
  ],
  input: {
    default: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#000000',
      borderWidth: 1,
      borderColor: '#CCCCCC',
      fontSize: 14,
      height: 30,
      padding: DEFAULT_PADDING,
      nsLabel: {
        fontSize: 14,
        color: '#000000',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: 'orange',
      },
    },
    hover: {
      width: '100%',
      backgroundColor: '#F0F0F0',
      color: '#000000',
      borderWidth: 1,
      borderColor: '#CCCCCC',
      fontSize: 14,
      height: 30,
      padding: DEFAULT_PADDING,
      nsLabel: {
        fontSize: 14,
        color: '#000000',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#CCCCCC',
      },
    },
    focus: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#000000',
      borderWidth: 1,
      borderColor: '#4C9AFF',
      fontSize: 14,
      height: 30,
      padding: DEFAULT_PADDING,
      nsLabel: {
        fontSize: 14,
        color: '#000000',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#CCCCCC',
      },
    },
    invalid: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#000000',
      borderWidth: 1,
      borderColor: '#FF4C4C',
      fontSize: 14,
      height: 30,
      padding: DEFAULT_PADDING,
      nsLabel: {
        fontSize: 14,
        color: '#000000',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#CCCCCC',
      },
    },
    valid: {
      width: '100%',
      backgroundColor: '#FFFFFF',
      color: '#000000',
      borderWidth: 1,
      borderColor: '#66FF66',
      fontSize: 14,
      height: 30,
      padding: DEFAULT_PADDING,
      nsLabel: {
        fontSize: 14,
        color: '#000000',
      },
      nsPlaceholder: {
        fontSize: 14,
        color: '#CCCCCC',
      },
    },
  },
};
